### ISSUE TITLE
hue plug-in reconnect

### ISSUE THREAD

**Issue by Boernsman** [guh/nymea-plugins#76]
The Hue bridge (V1) seems to have a bug that whenever the bridge gets disconnected from the LAN it loses the connection to all the clients. In case of the Hue app, I add a "new" bridge and do the push button authorization again - I could do that as well with nymea -> delete bridge -> discover bridge .. , but I've set-up a couple of rules depending on the Hue devices and then re-adding the bridge would require me to set-up the rules again. A rediscovery, re-authorization of the already added Hue bridge would solve that issue.

**Comment by t-mon** [comment]
The requested feature already exists, but the clients have not implemented that yet. The matching api method is: https://doc.nymea.io/jsonrpc.html#devices-reconfiguredevice
You could try it with nymea-cli in order to verify if there is an issue in the reconfigure procedure.

**Comment by Boernsman** [comment]
Tried the rediscover method with nymea-cli -  doesn't work

**Comment by Boernsman** [comment]
The bridge uses the IP address as ID that's why the rediscovery process doesn't work, recommend to use the MAC address to identify already set up bridges

**Comment by Boernsman** [comment]
Fixed by @mzanetti
